version: "3.9"
services:
  nginx:
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    volumes:
      - .:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker
      dockerfile: php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    volumes:
      - .:/var/www/html